<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vm</string>
	</array>
	<key>name</key>
	<string>Velocity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\\\#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>directive.language.velocity.escape</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\*\*</string>
			<key>end</key>
			<string>\*\#</string>
			<key>name</key>
			<string>comment.block.documentation</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#\*</string>
			<key>end</key>
			<string>\*\#</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>directive.language.velocity</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.velocity</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.velocity</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.array.json</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.array.velocity</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.velocity</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|while|for|in|foreach|return|else|case|macro|end|stop)\b</string>
					<key>name</key>
					<string>keyword.control.velocity</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(set|parse|cparse|config|include|cinclude)\b</string>
					<key>name</key>
					<string>keyword.velocity</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.velocity</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\$\{</string>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>source.velocity.embedded.source</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.velocity</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\$\!?\{?[[a-zA-Z]a-zA-Z0-9_]+(\}|\b)</string>
			<key>name</key>
			<string>variable.language.velocity</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.velocity</string>
	<key>uuid</key>
	<string>460426C7-D079-49DB-8E50-8E0B938644CA</string>
</dict>
</plist>
